###############################################################
#  Generated by:      Cadence Innovus 20.11-s130_1
#  OS:                Linux x86_64(Host ID kebab)
#  Generated on:      Fri Oct 14 15:09:06 2022
#  Design:            sha256
#  Command:           saveDesign save/clean_design_version_20_new.invs
###############################################################
set_global _enable_mmmc_by_default_flow      $CTE::mmmc_default
suppressMessage ENCEXT-2799
getVersion
getVersion
getVersion
win
set init_design_uniquify 1
set init_verilog ../run/netlist.v
set init_design_netlisttype Verilog
set init_design_settop 1
set init_top_cell sha256
set init_lef_file {../techlef//asap7_tech_4x_201209.lef ../lef/scaled//asap7sc7p5t_28_L_4x_220121a.lef ../lef/scaled//asap7sc7p5t_28_SL_4x_220121a.lef ../lef/scaled//asap7sc7p5t_28_R_4x_220121a.lef}
set fp_core_cntl aspect
set fp_aspect_ratio 1.0000
set extract_shrink_factor 1.0
set init_assign_buffer 0
set init_pwr_net VDD
set init_gnd_net VSS
set init_cpf_file {}
set init_mmmc_file ../scripts/sha256.mmmc
init_design
setDesignMode -process 7 -node N7
setMultiCpuUsage -localCpu 8
setNanoRouteMode -routeBottomRoutingLayer 2
setNanoRouteMode -routeTopRoutingLayer 7
globalNetConnect VDD -type pgpin -pin VDD -inst *
globalNetConnect VSS -type pgpin -pin VSS -inst *
floorPlan -site asap7sc7p5t -s 162.0 162.0 5.22 5.22 5.22 5.22 -noSnap
addWellTap -cell TAPCELL_ASAP7_75t_L -cellInterval 12.960 -inRowOffset 1.296
setPinAssignMode -pinEditInBatch true
editPin -fixOverlap 1 -unit MICRON -spreadDirection clockwise -side Left -layer 3 -spreadType center -spacing 2.016 -pin {reset_n clk {address[0]} {address[1]} {address[2]} {address[3]} {address[4]} {address[5]} {address[6]} {address[7]} cs we {write_data[0]} {write_data[1]} {write_data[2]} {write_data[3]} {write_data[4]} {write_data[5]} {write_data[6]} {write_data[7]} {write_data[8]} {write_data[9]} {write_data[10]} {write_data[11]} {write_data[12]} {write_data[13]} {write_data[14]} {write_data[15]} {write_data[16]} {write_data[17]} {write_data[18]} {write_data[19]} {write_data[20]} {write_data[21]} {write_data[22]} {write_data[23]} {write_data[24]} {write_data[25]} {write_data[26]} {write_data[27]} {write_data[28]} {write_data[29]} {write_data[30]} {write_data[31]}}
editPin -fixOverlap 1 -unit MICRON -spreadDirection clockwise -side Right -layer 3 -spreadType center -spacing 2 -pin {error {read_data[0]} {read_data[1]} {read_data[2]} {read_data[3]} {read_data[4]} {read_data[5]} {read_data[6]} {read_data[7]} {read_data[8]} {read_data[9]} {read_data[10]} {read_data[11]} {read_data[12]} {read_data[13]} {read_data[14]} {read_data[15]} {read_data[16]} {read_data[17]} {read_data[18]} {read_data[19]} {read_data[20]} {read_data[21]} {read_data[22]} {read_data[23]} {read_data[24]} {read_data[25]} {read_data[26]} {read_data[27]} {read_data[28]} {read_data[29]} {read_data[30]} {read_data[31]}}
editPin -snap TRACK -pin *
setPinAssignMode -pinEditInBatch false
legalizePin
setAddRingMode -ring_target default -extend_over_row 0 -ignore_rows 0 -avoid_short 0 -skip_crossing_trunks none -stacked_via_top_layer Pad -stacked_via_bottom_layer M1 -via_using_exact_crossover_size 1 -orthogonal_only true -skip_via_on_pin {  standardcell } -skip_via_on_wire_shape {  noshape }
addRing -nets {VDD VSS} -type core_rings -follow core -layer {top M7 bottom M7 left M6 right M6} -width 2.176 -spacing 0.384 -offset 0.384 -center 0 -threshold 0 -jog_distance 0 -snap_wire_center_to_grid None
addStripe -skip_via_on_wire_shape blockring -direction horizontal -set_to_set_distance 2.16 -skip_via_on_pin Standardcell -stacked_via_top_layer M1 -layer M2 -width 0.072 -nets VDD -stacked_via_bottom_layer M1 -start_from bottom -snap_wire_center_to_grid None -start_offset -0.044 -stop_offset -0.044
addStripe -skip_via_on_wire_shape blockring -direction horizontal -set_to_set_distance 2.16 -skip_via_on_pin Standardcell -stacked_via_top_layer M1 -layer M2 -width 0.072 -nets VSS -stacked_via_bottom_layer M1 -start_from bottom -snap_wire_center_to_grid None -start_offset 1.036 -stop_offset -0.044
addStripe -skip_via_on_wire_shape Noshape -set_to_set_distance 12.960 -skip_via_on_pin Standardcell -stacked_via_top_layer Pad -spacing 0.360 -xleft_offset 0.360 -layer M3 -width 0.936 -nets {VDD VSS} -stacked_via_bottom_layer M2 -start_from left
addStripe -skip_via_on_wire_shape Noshape -direction horizontal -set_to_set_distance 21.6 -skip_via_on_pin Standardcell -stacked_via_top_layer M7 -spacing 0.864 -layer M4 -width 0.864 -nets {VDD VSS} -stacked_via_bottom_layer M3 -start_from bottom
setSrouteMode -reset
setSrouteMode -viaConnectToShape { noshape }
sroute -connect { corePin } -layerChangeRange { M1(1) M7(1) } -blockPinTarget { nearestTarget } -floatingStripeTarget { blockring padring ring stripe ringpin blockpin followpin } -deleteExistingRoutes -allowJogging 0 -crossoverViaLayerRange { M1(1) Pad(10) } -nets { VDD VSS } -allowLayerChange 0 -targetViaLayerRange { M1(1) Pad(10) }
editPowerVia -add_vias 1 -orthogonal_only 0
verify_drc
setOptMode -holdTargetSlack 0.020
setOptMode -setupTargetSlack 0.020
colorizePowerMesh
place_opt_design
setTieHiLoMode -maxFanout 5
addTieHiLo -prefix TIE -cell {TIELOx1_ASAP7_75t_SL TIEHIx1_ASAP7_75t_SL}
ccopt_design
all_constraint_modes -active
set_interactive_constraint_modes [all_constraint_modes -active]
reset_propagated_clock [all_clocks]
update_io_latency -source -verbose
set_propagated_clock [all_clocks]
routeDesign
setAnalysisMode -analysisType onChipVariation
setSIMode -enable_glitch_report true
setSIMode -enable_glitch_propagation true
setSIMode -enable_delay_report true
optDesign -postRoute
optDesign -postRoute -hold
report_noise -threshold 0.2
report_noise -bumpy_waveform
report_timing
report_timing -early 
zoomBox 40.11250 63.96650 155.10650 166.91075
zoomBox 50.77875 75.65925 148.52375 163.16200
zoomBox 59.86400 85.59825 142.94725 159.97550
zoomBox 67.58650 94.04625 138.20725 157.26700
setLayerPreference node_layer -isVisible 0
setLayerPreference node_layer -isVisible 1
zoomBox 95.20575 119.28925 126.54100 147.34100
zoomBox 103.69825 129.40350 120.05575 144.04700
zoomBox 106.27025 132.46875 118.08875 143.04875
zoomBox 107.27475 133.66575 117.32050 142.65875
setLayerPreference node_layer -isVisible 0
setLayerPreference node_layer -isVisible 1
setLayerPreference node_layer -isVisible 0
setLayerPreference node_layer -isVisible 1
setLayerPreference node_layer -isVisible 0
uiSetTool move
deselectAll
deselectAll
deselectAll
ecoRoute
setLayerPreference node_layer -isVisible 1
zoomBox 91.64950 125.08000 121.87000 151.40675
zoomBox 75.88625 116.41900 125.09600 159.28825
zoomBox 68.67750 112.45800 126.57150 162.89250
zoomBox 38.48075 95.86650 132.75175 177.99075
zoomBox -32.97925 56.49425 147.61450 213.81875
zoomBox -126.26775 4.73925 167.79900 260.91600
zoomBox -219.12350 -46.77550 187.88950 307.79450
zoomBox -29.88050 95.77400 100.59900 209.44150
zoomBox 34.66900 137.75275 83.87950 180.62250
zoomBox 51.97625 149.35200 77.66500 171.73075
zoomBox 60.37700 155.00825 73.78675 166.69025
zoomBox 61.75300 155.93475 73.15150 165.86450
zoomBox 62.92250 156.72225 72.61150 165.16275
zoomBox 63.91675 157.39175 72.15250 164.56625
setLayerPreference node_layer -isVisible 0
zoomBox 61.09975 155.80800 72.49875 165.73825
zoomBox 59.30825 154.80100 72.71900 166.48375
zoomBox 57.20050 153.61625 72.97800 167.36075
zoomBox 54.72100 152.22250 73.28275 168.39250
deselectAll
deselectAll
ecoRoute
setLayerPreference node_layer -isVisible 1
zoomBox 56.93700 153.59725 72.71450 167.34175
zoomBox 54.40025 152.31750 72.96225 168.48775
setLayerPreference node_layer -isVisible 0
deselectAll
ecoRoute
setLayerPreference node_layer -isVisible 1
setLayerPreference node_layer -isVisible 0
zoomBox 43.78775 147.06450 74.01275 173.39500
zoomBox 47.91300 149.10650 73.60425 171.48750
zoomBox 38.93450 144.66225 74.49325 175.63925
zoomBox 52.52575 151.13875 71.08775 167.30900
zoomBox 38.99775 144.45225 74.55675 175.42950
zoomBox 13.08275 131.64300 81.20250 190.98575
zoomBox 38.25925 142.91250 80.09350 179.35650
zoomBox 49.52400 147.83675 79.74925 174.16750
zoomBox 53.91300 149.75975 79.60450 172.14100
zoomBox 60.79475 152.77550 79.35700 168.94600
deselectAll
deselectAll
ecoRoute
setLayerPreference node_layer -isVisible 1
zoomBox 44.41800 144.31800 86.25300 180.76275
zoomBox 17.46650 130.55825 97.61000 200.37550
zoomBox 19.93425 144.18650 61.77000 180.63175
zoomBox 22.38225 149.89300 48.07475 172.27500
zoomBox 22.96675 151.25525 44.80525 170.28000
zoomBox 25.97400 153.74400 39.38575 165.42775
zoomBox 27.30200 154.84275 36.99225 163.28450
setLayerPreference node_layer -isVisible 0
ecoRoute
setLayerPreference node_layer -isVisible 1
zoomBox 16.11825 151.50175 37.95800 170.52750
zoomBox -2.30675 145.93775 39.53150 182.38525
zoomBox -26.61700 138.56350 41.51000 197.91250
zoomBox -50.81425 131.31800 43.47925 213.46200
zoomBox -105.60325 115.10425 47.93800 248.86200
panPage 1 0
panPage 1 0
panPage 0 -1
panPage 0 -1
zoomBox 36.34825 62.18400 130.64200 144.32825
zoomBox 57.47200 74.23775 125.59975 133.58725
zoomBox 65.72175 78.94525 123.63050 129.39250
zoomBox 78.64950 86.28575 120.48875 122.73400
zoomBox 91.53550 93.55725 117.23025 115.94125
zoomBox 94.54125 95.22275 116.38200 114.24925
zoomBox 97.09650 96.63850 115.66100 112.81100
zoomBox 99.26825 97.84175 115.04825 111.58850
zoomBox 102.68350 99.73425 114.08450 109.66625
zoomBox 104.01725 100.47325 113.70825 108.91550
zoomBox 106.11450 101.63525 113.11625 107.73475
setLayerPreference node_layer -isVisible 0
ecoRoute
setLayerPreference node_layer -isVisible 1
zoomBox 96.47225 96.27850 115.03800 112.45200
zoomBox 86.97525 90.79825 117.20625 117.13400
zoomBox 82.63200 88.29200 118.19775 119.27525
zoomBox 56.11750 72.99250 124.25050 132.34675
zoomBox 5.32425 43.68300 135.84600 157.38725
zoomBox -61.44425 5.15525 151.08875 190.30375
zoomBox 141.39525 146.19775 159.08600 128.50675
setLayerPreference node_layer -isVisible 0
ecoRoute
setLayerPreference node_layer -isVisible 1
zoomBox 117.39050 113.55425 171.23625 160.46200
zoomBox 94.74475 98.47000 182.42375 174.85175
zoomBox 120.79725 115.81675 166.56675 155.68900
zoomBox 136.89950 126.36425 157.20800 144.05600
zoomBox 140.86450 128.79975 155.53725 141.58200
zoomBox 144.84800 131.24675 153.85875 139.09650
setLayerPreference node_layer -isVisible 0
zoomBox 132.20425 124.71375 156.09675 145.52775
zoomBox 128.88700 122.85800 156.99575 147.34500
zoomBox 124.98425 120.67475 158.05350 149.48300
zoomBox 120.39275 118.10600 159.29775 151.99825
zoomBox 114.99100 115.08425 160.76175 154.95750
zoomBox 135.02375 126.29100 155.33250 143.98300
zoomBox 145.38075 131.23700 154.39225 139.08750
zoomBox 149.53600 133.48900 153.53475 136.97250
ecoRoute
setLayerPreference node_layer -isVisible 1
zoomBox 143.39675 130.12175 155.87125 140.98900
zoomBox 125.79025 118.69525 164.70450 152.59550
zoomBox 102.21625 103.13325 176.76400 168.07575
zoomBox 57.07075 73.32175 199.88150 197.73150
zoomBox -2.27375 34.13375 230.26975 236.71450
zoomBox 140.11600 107.05225 153.37400 94.85500
zoomBox 142.73800 97.62700 151.33675 105.11775
zoomBox 143.45275 98.28875 150.76175 104.65600
zoomBox 144.06025 98.85125 150.27300 104.26350
setLayerPreference node_layer -isVisible 0
zoomBox 142.84400 97.71925 151.44300 105.21025
zoomBox 141.16050 96.15275 153.06225 106.52100
zoomBox 140.08975 95.15650 154.09200 107.35450
zoomBox 138.83025 93.98425 155.30350 108.33500
ecoRoute
setLayerPreference node_layer -isVisible 1
setLayerPreference node_layer -isVisible 0
ecoRoute
setLayerPreference node_layer -isVisible 1
zoomBox 107.33550 81.44575 158.72250 126.21150
zoomBox 55.07250 57.03325 170.88625 157.92450
zoomBox -96.74050 -15.37250 210.33700 252.13850
zoomBox -316.26700 -121.81950 271.99725 390.64775
zoomBox 124.42800 98.86325 170.71125 76.72800
zoomBox 126.58125 71.30100 165.92200 105.57275
zoomBox 120.23875 58.19425 184.29875 114.00025
zoomBox 114.17850 45.14825 202.84325 122.38875
zoomBox 127.17200 71.36725 166.51300 105.63925
zoomBox 132.16800 81.38025 152.70450 99.27075
zoomBox 134.77575 86.60700 145.49625 95.94625
zoomBox 135.20450 87.46325 144.31725 95.40175
setLayerPreference node_layer -isVisible 0
zoomBox 132.18750 83.50250 149.64525 98.71075
zoomBox 131.08800 82.03400 151.62650 99.92625
deselectAll
deselectAll
deselectAll
zoomBox 134.32975 87.54450 143.44300 95.48350
panPage 1 0
panPage 1 0
deselectAll
deselectAll
deselectAll
zoomBox 126.73700 81.16225 150.90075 102.21250
ecoRoute
setLayerPreference node_layer -isVisible 1
zoomBox 137.07550 85.95600 149.68900 96.94425
zoomBox 135.08300 85.03200 149.92250 97.95950
setLayerPreference node_layer -isVisible 0
ecoRoute
setLayerPreference node_layer -isVisible 1
setLayerPreference node_layer -isVisible 0
deselectAll
deselectAll
ecoRoute
setLayerPreference node_layer -isVisible 1
zoomBox 132.74500 83.88250 150.20325 99.09125
zoomBox 129.99425 82.53000 150.53350 100.42275
zoomBox 126.75800 80.93875 150.92200 101.98925
zoomBox 122.95075 79.06675 151.37900 103.83200
zoomBox 118.47175 76.86425 151.91675 106.00000
zoomBox 113.20225 74.27325 152.54925 108.55050
zoomBox 107.00275 71.22500 153.29350 111.55125
zoomBox 99.70925 67.63875 154.16900 115.08150
zoomBox 91.12875 63.41975 155.19900 119.23475
zoomBox 55.00200 45.74675 159.33025 136.63250
zoomBox 38.48050 37.66425 161.21975 144.58875
zoomBox 70.73300 52.26700 159.41225 129.52000
zoomBox 103.19600 66.93750 157.65625 114.38075
zoomBox 110.94575 70.43975 157.23700 110.76650
zoomBox 130.66125 80.84600 154.82650 101.89750
zoomBox 141.78725 87.36025 152.50950 96.70100
setLayerPreference node_layer -isVisible 0
zoomBox 137.41575 84.43325 154.87550 99.64325
zoomBox 130.31525 79.66700 158.74575 104.43425
zoomBox 113.48350 68.35675 167.94800 115.80350
zoomBox 118.76525 71.90575 165.06025 112.23575
zoomBox 123.25475 74.92250 162.60550 109.20300
zoomBox 127.07075 77.48675 160.51900 106.62525
zoomBox 133.07175 81.51925 157.23800 102.57175
zoomBox 135.41525 83.09400 155.95675 100.98875
deselectAll
deselectAll
deselectAll
zoomBox 139.41025 85.65175 152.02525 96.64125
zoomBox 140.36400 86.26225 151.08675 95.60350
zoomBox 141.17475 86.78125 150.28900 94.72125
zoomBox 138.49050 84.76325 153.33200 97.69250
deselectAll
deselectAll
undo
deselectAll
deselectAll
zoomBox 133.99500 87.31550 154.53700 105.21075
zoomBox 128.08425 85.45350 156.51600 110.22175
ecoRoute
setLayerPreference node_layer -isVisible 1
zoomBox 119.36800 81.82975 158.72000 116.11125
zoomBox 99.63175 73.62500 163.71050 129.44725
zoomBox 45.85900 52.37225 190.27625 178.18150
zoomBox 132.97050 92.05800 143.50950 86.13000
setLayerPreference node_layer -isVisible 0
zoomBox 131.49025 83.83750 143.88900 94.63875
zoomBox 130.05825 83.00675 144.64500 95.71400
zoomBox 128.45550 82.00575 145.61650 96.95550
deselectAll
deselectAll
zoomBox 133.24500 85.79350 140.85950 92.42700
ecoRoute
setLayerPreference node_layer -isVisible 1
zoomBox 127.84125 83.51100 142.42900 96.21925
zoomBox 117.59000 79.13950 145.53600 103.48475
zoomBox 97.95250 70.76500 151.48850 117.40300
zoomBox 60.33350 54.72225 162.89175 144.06600
zoomBox 10.88225 33.63350 177.88150 179.11525
zoomBox -38.33925 12.64300 192.80175 214.00175
zoomBox 25.96900 95.40025 41.25550 87.49350
zoomBox 27.23450 85.94150 40.22800 97.26075
zoomBox 29.22425 87.75450 38.61200 95.93275
setLayerPreference node_layer -isVisible 0
setLayerPreference node_layer -isVisible 1
setLayerPreference node_layer -isVisible 0
setLayerPreference node_layer -isVisible 1
zoomBox 27.79600 87.15000 38.84050 96.77150
zoomBox 24.21175 85.58775 39.49825 98.90450
zoomBox 21.98475 84.57575 39.96875 100.24250
zoomBox 19.36475 83.38525 40.52250 101.81675
zoomBox 16.28250 81.98450 41.17400 103.66875
zoomBox 24.78625 85.82375 40.07300 99.14075
zoomBox 26.92250 86.74925 39.91625 98.06875
zoomBox 13.91625 81.63800 43.20150 107.15000
zoomBox -15.39025 70.12475 50.61150 127.62225
zoomBox -81.43925 44.17725 67.31225 173.76225
zoomBox -156.04125 14.86950 86.17575 225.87725
zoomBox -525.03975 -76.35425 117.19150 483.12650
zoomBox -897.28600 -168.38100 148.48050 742.64025
zoomBox -1067.52400 -210.46700 162.78975 861.32275
zoomBox -1503.42700 -318.23050 199.42950 1165.21575
zoomBox -629.58725 -102.20100 125.97925 556.01200
zoomBox -196.00850 5.12000 88.95325 253.36500
zoomBox -83.64325 53.19525 65.10875 182.78075
zoomBox -18.92525 82.60875 47.07700 140.10675
zoomBox 10.17525 91.64050 39.46125 117.15300
zoomBox -28.65025 86.18000 49.00225 153.82700
zoomBox 30.14250 96.45100 39.79375 86.62250
setLayerPreference node_layer -isVisible 0
setLayerPreference node_layer -isVisible 1
zoomBox 31.23800 88.72725 38.16675 94.76325
zoomBox 29.19250 86.39400 40.47500 96.22275
zoomBox 26.89925 84.33900 42.51550 97.94300
setLayerPreference node_layer -isVisible 0
zoomBox 24.38225 83.33650 42.75425 99.34125
zoomBox 21.42100 82.15700 43.03525 100.98625
zoomBox 17.93700 80.76950 43.36575 102.92175
zoomBox 9.01675 77.21700 44.21225 107.87750
zoomBox 3.34400 74.95775 44.75050 111.02900
zoomBox 19.24875 81.11950 44.67775 103.27200
zoomBox 23.04575 82.59400 44.66025 101.42350
zoomBox 29.01650 84.91250 44.63300 98.51675
zoomBox 31.34825 85.81775 44.62225 97.38150
zoomBox 28.67150 83.57350 47.04425 99.57900
zoomBox 30.11375 84.78650 45.73075 98.39125
zoomBox 34.26950 86.16000 45.55275 95.98950
zoomBox 35.89250 86.69650 45.48325 95.05150
zoomBox 39.44100 87.86925 45.33125 93.00050
zoomBox 35.89175 86.69575 45.48325 95.05150
zoomBox 32.35900 85.52800 45.63450 97.09300
deselectAll
deselectAll
ecoRoute
setLayerPreference node_layer -isVisible 1
zoomBox 24.20500 81.69950 49.63725 103.85475
zoomBox 13.52750 76.67025 54.93975 112.74650
zoomBox -3.85975 68.48100 63.57375 127.22575
zoomBox -32.17150 55.14650 77.63300 150.80275
zoomBox -60.35175 41.87375 91.62675 174.27000
zoomBox -124.92175 14.07675 122.55050 229.66250
zoomBox 37.61425 78.97825 53.98075 65.15125
zoomBox 39.59975 68.99300 49.65125 77.74950
zoomBox 40.08100 69.93350 48.62500 77.37650
zoomBox 39.41575 69.10475 49.46750 77.86125
zoomBox 37.71225 66.98300 51.62450 79.10275
zoomBox 36.62875 65.63375 52.99625 79.89225
setLayerPreference node_layer -isVisible 0
panPage -1 0
setLayerPreference node_layer -isVisible 1
setLayerPreference node_layer -isVisible 0
setLayerPreference node_layer -isVisible 1
setLayerPreference node_layer -isVisible 0
setLayerPreference node_layer -isVisible 1
setLayerPreference node_layer -isVisible 0
deselectAll
deselectAll
ecoRoute
setLayerPreference node_layer -isVisible 1
setLayerPreference node_layer -isVisible 0
zoomBox 29.03425 64.73100 48.29025 81.50600
zoomBox 17.79025 60.95075 49.14550 88.26600
zoomBox -8.89200 51.98000 51.17550 104.30800
zoomBox -30.33200 44.77175 52.80675 117.19825
setLayerPreference node_layer -isVisible 1
zoomBox 39.25050 75.39175 49.96275 65.34325
zoomBox 37.28650 64.43800 50.85675 76.25975
setLayerPreference node_layer -isVisible 0
setLayerPreference node_layer -isVisible 1
setLayerPreference node_layer -isVisible 0
setLayerPreference node_layer -isVisible 1
setLayerPreference node_layer -isVisible 0
zoomBox 32.36325 62.32800 51.14575 78.69050
deselectAll
zoomBox 39.77500 66.12575 49.57975 74.66725
deselectAll
ecoRoute
setLayerPreference node_layer -isVisible 1
zoomBox 32.70175 62.86225 51.48525 79.22550
zoomBox 15.30075 54.26900 57.63450 91.14800
zoomBox -23.91625 34.66025 71.49375 117.77675
zoomBox -88.46925 2.38325 94.30650 161.60875
zoomBox -133.77600 -23.23175 119.20100 197.14950
zoomBox -338.47200 -138.96125 231.67525 357.72350
zoomBox -403.40675 -175.67350 267.35475 408.66150
zoomBox 18.01800 72.89825 49.37650 50.71800
zoomBox 24.13750 53.04700 43.39550 69.82375
setLayerPreference node_layer -isVisible 0
setLayerPreference node_layer -isVisible 1
setLayerPreference node_layer -isVisible 0
setLayerPreference node_layer -isVisible 1
setLayerPreference node_layer -isVisible 0
deselectAll
deselectAll
deselectAll
deselectAll
zoomBox 31.93575 56.32175 41.98875 65.07950
ecoRoute
setLayerPreference node_layer -isVisible 1
zoomBox 23.53850 52.72775 46.19550 72.46550
zoomBox 14.05800 48.68575 50.95150 80.82550
zoomBox 4.62175 44.66225 55.68575 89.14675
zoomBox -8.43875 39.09350 62.23850 100.66400
zoomBox -26.51550 31.38600 71.30775 116.60500
zoomBox -51.53550 20.71800 83.86050 138.66850
zoomBox -86.16525 5.95300 101.23450 169.20650
zoomBox -164.57575 -27.47925 140.57400 238.35250
zoomBox -242.62200 -60.75575 179.73075 307.17750
zoomBox -292.25400 -81.91750 204.63175 350.94525
zoomBox 145.14150 61.99225 175.17000 46.69475
zoomBox 152.99125 44.83475 171.43275 60.90000
zoomBox 155.96150 46.62600 169.28550 58.23325
setLayerPreference node_layer -isVisible 0
setLayerPreference node_layer -isVisible 1
setLayerPreference node_layer -isVisible 0
ecoRoute
setLayerPreference node_layer -isVisible 1
zoomBox 137.10800 39.47750 178.67100 75.68525
zoomBox 91.47775 22.10225 201.68150 118.10650
zoomBox -0.05675 -13.18825 248.31525 203.18150
zoomBox -51.82200 -39.24425 291.94575 260.22950
verify_drc
setLayerPreference violation -isVisible 1
violationBrowser -all -no_display_false -displayByLayer
violationBrowserClose
verify_drc -check_uncolored
verify_drc
clearDrc
verify_drc
setLayerPreference violation -isVisible 1
violationBrowser -all -no_display_false -displayByLayer
violationBrowserClose
verify_geometry_pvs
verify_connectivity
checkPlace
saveDesign save/clean_design_version_20_new.invs
###############################################################
#  Generated by:      Cadence Innovus 20.11-s130_1
#  OS:                Linux x86_64(Host ID kebab)
#  Generated on:      Tue Oct 18 16:28:00 2022
#  Design:            sha256
#  Command:           saveDesign save/sha256_v20.enc
###############################################################
set_global _enable_mmmc_by_default_flow      $CTE::mmmc_default
suppressMessage ENCEXT-2799
getVersion
getVersion
getVersion
win
is_common_ui_mode
restoreDesign /home/eslami/Desktop/ispd23/asap7_reference_design/work/save/clean_design_version_20_new.invs.dat sha256
setLayerPreference violation -isVisible 1
violationBrowser -all -no_display_false -displayByLayer
violationBrowserClose
saveDesign save/sha256_v20.enc
###############################################################
#  Generated by:      Cadence Innovus 20.11-s130_1
#  OS:                Linux x86_64(Host ID kebab)
#  Generated on:      Wed Oct 19 18:08:37 2022
#  Design:            sha256
#  Command:           saveDesign ../test/sha256_v20.enc -tgz
###############################################################
set_global _enable_mmmc_by_default_flow      $CTE::mmmc_default
suppressMessage ENCEXT-2799
getVersion
getVersion
getVersion
win
is_common_ui_mode
restoreDesign /home/eslami/Desktop/ispd23/asap7_reference_design/work/save/sha256_v20.enc.dat sha256
clearDrc
saveDesign ../test/sha256_v20.enc -tgz
